# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/railfence.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os
os.environ['QT_QPA_PLATFORM_PLUGIN_PATH'] = 'C:/Users/HP/AppData/Local/Programs/Python/Python39/Lib/site-packages/PyQt5/Qt/plugins/platforms'


class Ui_railfence(object):
    def setupUi(self, railfence):
        railfence.setObjectName("railfence")
        railfence.resize(800, 426)
        self.centralwidget = QtWidgets.QWidget(railfence)
        self.centralwidget.setObjectName("centralwidget")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(170, 60, 581, 87))
        self.textEdit.setObjectName("textEdit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(300, 20, 231, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 180, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(40, 240, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.decryptButton = QtWidgets.QPushButton(self.centralwidget)
        self.decryptButton.setGeometry(QtCore.QRect(600, 340, 93, 28))
        self.decryptButton.setObjectName("decryptButton")
        self.textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_2.setGeometry(QtCore.QRect(170, 230, 581, 87))
        self.textEdit_2.setObjectName("textEdit_2")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(170, 180, 581, 22))
        self.lineEdit.setObjectName("lineEdit")
        self.encryptButton = QtWidgets.QPushButton(self.centralwidget)
        self.encryptButton.setGeometry(QtCore.QRect(240, 340, 93, 28))
        self.encryptButton.setObjectName("encryptButton")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 70, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        railfence.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(railfence)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        railfence.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(railfence)
        self.statusbar.setObjectName("statusbar")
        railfence.setStatusBar(self.statusbar)

        self.retranslateUi(railfence)
        QtCore.QMetaObject.connectSlotsByName(railfence)

    def retranslateUi(self, railfence):
        _translate = QtCore.QCoreApplication.translate
        railfence.setWindowTitle(_translate("railfence", "Rail Fence Cipher"))
        self.label.setText(_translate("railfence", "RAIL FENCE CIPHER"))
        self.label_3.setText(_translate("railfence", "Key:"))
        self.label_4.setText(_translate("railfence", "Cipher Text:"))
        self.decryptButton.setText(_translate("railfence", "Decrypt"))
        self.encryptButton.setText(_translate("railfence", "Encrypt"))
        self.label_2.setText(_translate("railfence", "Plain Text:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    railfence = QtWidgets.QMainWindow()
    ui = Ui_railfence()
    ui.setupUi(railfence)
    railfence.show()
    sys.exit(app.exec_())
