# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/rsa.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1100, 598)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(460, 30, 181, 91))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(60, 140, 47, 13))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(56, 240, 61, 20))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(576, 140, 61, 20))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(580, 250, 61, 20))
        self.label_5.setObjectName("label_5")
        self.textEdit_Plaintext = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_Plaintext.setGeometry(QtCore.QRect(130, 140, 321, 71))
        self.textEdit_Plaintext.setObjectName("textEdit_Plaintext")
        self.textEdit_Infmation = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_Infmation.setGeometry(QtCore.QRect(670, 140, 391, 71))
        self.textEdit_Infmation.setObjectName("textEdit_Infmation")
        self.textEdit_Ciphertext = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_Ciphertext.setGeometry(QtCore.QRect(133, 240, 321, 71))
        self.textEdit_Ciphertext.setObjectName("textEdit_Ciphertext")
        self.textEdit_Signature = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_Signature.setGeometry(QtCore.QRect(670, 240, 391, 71))
        self.textEdit_Signature.setObjectName("textEdit_Signature")
        self.pushButton_Encrypt = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Encrypt.setGeometry(QtCore.QRect(150, 360, 75, 23))
        self.pushButton_Encrypt.setObjectName("pushButton_Encrypt")
        self.pushButton_Decrypt = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Decrypt.setGeometry(QtCore.QRect(330, 360, 75, 23))
        self.pushButton_Decrypt.setObjectName("pushButton_Decrypt")
        self.pushButton_Sign = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Sign.setGeometry(QtCore.QRect(720, 360, 75, 23))
        self.pushButton_Sign.setObjectName("pushButton_Sign")
        self.pushButton_Verify = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Verify.setGeometry(QtCore.QRect(930, 360, 75, 23))
        self.pushButton_Verify.setObjectName("pushButton_Verify")
        self.pushButton_Generatekeys = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Generatekeys.setGeometry(QtCore.QRect(660, 70, 101, 23))
        self.pushButton_Generatekeys.setObjectName("pushButton_Generatekeys")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1100, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "RSA CIPHER"))
        self.label_2.setText(_translate("MainWindow", "Plain Text: "))
        self.label_3.setText(_translate("MainWindow", "Cipher Text: "))
        self.label_4.setText(_translate("MainWindow", "Information:"))
        self.label_5.setText(_translate("MainWindow", "Signature:"))
        self.pushButton_Encrypt.setText(_translate("MainWindow", "Encrypt"))
        self.pushButton_Decrypt.setText(_translate("MainWindow", "Decrypt"))
        self.pushButton_Sign.setText(_translate("MainWindow", "Sign"))
        self.pushButton_Verify.setText(_translate("MainWindow", "Verify"))
        self.pushButton_Generatekeys.setText(_translate("MainWindow", "Generate Keys"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
