# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/vigenere.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_vigenere(object):
    def setupUi(self, vigenere):
        vigenere.setObjectName("vigenere")
        vigenere.resize(800, 427)
        self.centralwidget = QtWidgets.QWidget(vigenere)
        self.centralwidget.setObjectName("centralwidget")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 180, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(170, 60, 581, 87))
        self.textEdit.setObjectName("textEdit")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(40, 240, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_2.setGeometry(QtCore.QRect(170, 230, 581, 87))
        self.textEdit_2.setObjectName("textEdit_2")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(170, 180, 581, 22))
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(300, 20, 221, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(600, 340, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(240, 340, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 70, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        vigenere.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(vigenere)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        vigenere.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(vigenere)
        self.statusbar.setObjectName("statusbar")
        vigenere.setStatusBar(self.statusbar)

        self.retranslateUi(vigenere)
        QtCore.QMetaObject.connectSlotsByName(vigenere)

    def retranslateUi(self, vigenere):
        _translate = QtCore.QCoreApplication.translate
        vigenere.setWindowTitle(_translate("vigenere", "Vigenere Cipher"))
        self.label_3.setText(_translate("vigenere", "Key:"))
        self.label_4.setText(_translate("vigenere", "Cipher Text:"))
        self.label.setText(_translate("vigenere", "VIGENERE CIPHER"))
        self.pushButton_2.setText(_translate("vigenere", "Decrypt"))
        self.pushButton.setText(_translate("vigenere", "Encrypt"))
        self.label_2.setText(_translate("vigenere", "Plain Text:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    vigenere = QtWidgets.QMainWindow()
    ui = Ui_vigenere()
    ui.setupUi(vigenere)
    vigenere.show()
    sys.exit(app.exec_())
